### ISSUE TITLE
SyntaxError: invalid syntax

### ISSUE THREAD

**Issue by SaeedHK** [adamyala/Your_First_Decentralized_Application_Python#10]
Hello,
I have an error when I do `$ python main.py`. I followed your instructions as you described. I set up my virtual environment with 
```
$ virtualenv -p /usr/bin/python3.6 venv
$ source venv/bin/activate
```
and the rest I followed your instructions. I tried first
```
(venv) $ python main.py 
Traceback (most recent call last):
  File "main.py", line 45, in <module>
    compiled_code = compile_source(''.join(source_code))
  File "/home/saeed/anaconda3/lib/python3.7/site-packages/solc/main.py", line 108, in compile_source
    stdoutdata, stderrdata, command, proc = solc_wrapper(**compiler_kwargs)
  File "/home/saeed/anaconda3/lib/python3.7/site-packages/solc/utils/string.py", line 85, in inner
    return force_obj_to_text(fn(*args, **kwargs))
  File "/home/saeed/anaconda3/lib/python3.7/site-packages/solc/wrapper.py", line 159, in solc_wrapper
    stderr=subprocess.PIPE)
  File "/home/saeed/anaconda3/lib/python3.7/subprocess.py", line 769, in __init__
    restore_signals, start_new_session)
  File "/home/saeed/anaconda3/lib/python3.7/subprocess.py", line 1516, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
PermissionError: [Errno 13] Permission denied: 'solc'
```
but then tried with `sudo` and got the following:
```
(venv) $ sudo python main.py 
[sudo] password for saeed: 
  File "main.py", line 51
    contract_bytecode = compiled_code[f'<stdin>:{contract_name}']['bin']
                                                               ^
SyntaxError: invalid syntax
```
I'm new to solidity and smart contracts and I cannot understand where the error comes from. Do you have any idea ? Thanks in advance.
(I tried many setups and many instructions from many manuals, for just trying a simple smart contract, but still no success)

**Comment by adamyala** [comment]
@saeedhadikhanloo Thank you for raising the issue. Unfortunately I don't think it's an issue with the code in the repo.

For `PermissionError: [Errno 13] Permission denied: 'solc'`, I'd look at fixing the permissions for the `solc` package on the machine this is running on. Running `python` as `sudo` might fix this issue but...

For `SyntaxError: invalid syntax`, you most likely are running python 2 on the machine. This tutorial requires python 3. You might already have python 3 installed! Try `python3` on the command line. If it is installed, then you'll have to look into creating a new venv with it.

Once you're on python 3, `sudo python main.py` might work, but it's always best to fix the permissions of your dependancies instead.

Does that help at all?

**Comment by SaeedHK** [comment]
@adamyala 
Thanks a lot for your response. You're absolutely right. The error can be fixed by changing the access permission for `solc`. It can be fixed with the following command in the terminal:
``` 
$ sudo chmod a+x $(which solc) 
```
