### ISSUE TITLE
TypeError: One or more arguments could not be encoded to the necessary ABI type.  Expected types are: bytes32[]

### ISSUE THREAD

**Issue by datafatmunger** [adamyala/Your_First_Decentralized_Application_Python#3]
This is great! Thank you for putting it together.

One strange thing is I was getting the error above, using Python 3.6.4 on Linux.  I was able to fix it by changing main.py line 57 to:

```
    args=[
        [str.encode('Rama'), str.encode('Nick'), str.encode('Jose')],
    ],
```
Unrelated...but I also changed requirements.txt to contain web3 4.0.0b.

**Comment by adamyala** [comment]
Thank you for the bug report! I pushed a fix. Could you reinstall the reqs and give it another go?

> Unrelated...but I also changed requirements.txt to contain web3 4.0.0b.

Very related actually. Thank you for pointing this out. Some of the packages in `requirements.txt` actually broke when I reinstalled them so I updated the requirements to the latest web3py beta.
