### ISSUE TITLE
UnicodeDecodeError: 'utf8' codec ("utf8") can't decode byte 0xc6 in position 109: invalid continuation byte

### ISSUE THREAD

**Issue by djalmabright** [adamyala/Your_First_Decentralized_Application_Python#7]
Trying  to  run  -  python  main.py  in  Windows  10  I   get  this  fatal  error :  
UnicodeDecodeError: 'utf8' codec ("utf8") can't decode byte 0xc6 in position 109: invalid continuation byte

**Comment by adamyala** [comment]
@djalmabright Could we have more info?

What's your version of python?
Are you using the versions specified in `requirements.txt`?

**Comment by djalmabright** [comment]
Python3.6 ! this is specified in requirements of repo...

**Comment by adamyala** [comment]
@djalmabright I'm having some trouble recreating. Could you post a full stack trace? Then I can find the specific line that's causing issues and investigate that in depth.

Thank you again for reporting this bug. I'm sure some other folks have had it as well.

**Comment by djalmabright** [comment]
This  is full  stack  trace   in  Windows 10 👍 

C:\Users\Administrador\Decentralized_Application_>python  main.py
Traceback (most recent call last):
  File "main.py", line 9, in <module>
    from web3 import Web3, HTTPProvider
ModuleNotFoundError: No module named 'web3'

C:\Users\Administrador\Decentralized_Application_>pip install web3
Collecting web3
  Downloading web3-3.16.5-py3-none-any.whl (73kB)
    100% |████████████████████████████████| 81kB 783kB/s
Collecting cytoolz>=0.8.2 (from web3)
  Using cached cytoolz-0.9.0.tar.gz
Collecting lru-dict>=1.1.6 (from web3)
  Using cached lru-dict-1.1.6.tar.gz
Collecting eth-tester==0.1.0b11 (from web3)
  Using cached eth_tester-0.1.0b11-py3-none-any.whl
Collecting eth-abi<0.6.0,>=0.5.0 (from web3)
  Using cached eth_abi-0.5.0-py3-none-any.whl
Collecting eth-utils<1.0.0,>=0.7.1 (from web3)
  Downloading eth_utils-0.8.0-py3-none-any.whl
Collecting pysha3>=0.3 (from web3)
  Using cached pysha3-1.0.2-cp36-cp36m-win32.whl
Collecting rlp>=0.4.7 (from web3)
  Using cached rlp-0.6.0.tar.gz
Requirement already satisfied: toolz>=0.8.2 in c:\users\administrador\appdata\local\programs\python\python36-32\lib\site-packages (from web3)
Collecting requests>=2.12.4 (from web3)
  Using cached requests-2.18.4-py2.py3-none-any.whl
Requirement already satisfied: semantic-version<3.0.0,>=2.6.0 in c:\users\administrador\appdata\local\programs\python\python36-32\lib\site-packages (from eth-tester==0.1.0b11->web3)
Collecting eth-keys<0.2.0,>=0.1.0b3 (from eth-tester==0.1.0b11->web3)
  Using cached eth_keys-0.1.0b4-py3-none-any.whl
Requirement already satisfied: certifi>=2017.4.17 in c:\users\administrador\appdata\local\programs\python\python36-32\lib\site-packages (from requests>=2.12.4->web3)
Requirement already satisfied: chardet<3.1.0,>=3.0.2 in c:\users\administrador\appdata\local\programs\python\python36-32\lib\site-packages (from requests>=2.12.4->web3)
Collecting idna<2.7,>=2.5 (from requests>=2.12.4->web3)
  Using cached idna-2.6-py2.py3-none-any.whl
Collecting urllib3<1.23,>=1.21.1 (from requests>=2.12.4->web3)
  Using cached urllib3-1.22-py2.py3-none-any.whl
Installing collected packages: cytoolz, lru-dict, rlp, pysha3, eth-utils, eth-keys, eth-tester, eth-abi, idna, urllib3, requests, web3
  Running setup.py install for cytoolz ... error
    Complete output from command c:\users\administrador\appdata\local\programs\python\python36-32\python.exe -u -c "import setuptools, tokenize;__file__='C:\\Users\\ADMINI~1\\AppData\\Local\\Temp\\pip-build-qk95p6mk\\cytoolz\\setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record C:\Users\ADMINI~1\AppData\Local\Temp\pip-5td6dish-record\install-record.txt --single-version-externally-managed --compile:
    running install
    running build
    running build_py
    creating build
    creating build\lib.win32-3.6
    creating build\lib.win32-3.6\cytoolz
    copying cytoolz\compatibility.py -> build\lib.win32-3.6\cytoolz
    copying cytoolz\utils_test.py -> build\lib.win32-3.6\cytoolz
    copying cytoolz\_signatures.py -> build\lib.win32-3.6\cytoolz
    copying cytoolz\_version.py -> build\lib.win32-3.6\cytoolz
    copying cytoolz\__init__.py -> build\lib.win32-3.6\cytoolz
    creating build\lib.win32-3.6\cytoolz\curried
    copying cytoolz\curried\exceptions.py -> build\lib.win32-3.6\cytoolz\curried
    copying cytoolz\curried\operator.py -> build\lib.win32-3.6\cytoolz\curried
    copying cytoolz\curried\__init__.py -> build\lib.win32-3.6\cytoolz\curried
    copying cytoolz\dicttoolz.pyx -> build\lib.win32-3.6\cytoolz
    copying cytoolz\functoolz.pyx -> build\lib.win32-3.6\cytoolz
    copying cytoolz\itertoolz.pyx -> build\lib.win32-3.6\cytoolz
    copying cytoolz\recipes.pyx -> build\lib.win32-3.6\cytoolz
    copying cytoolz\utils.pyx -> build\lib.win32-3.6\cytoolz
    copying cytoolz\cpython.pxd -> build\lib.win32-3.6\cytoolz
    copying cytoolz\dicttoolz.pxd -> build\lib.win32-3.6\cytoolz
    copying cytoolz\functoolz.pxd -> build\lib.win32-3.6\cytoolz
    copying cytoolz\itertoolz.pxd -> build\lib.win32-3.6\cytoolz
    copying cytoolz\recipes.pxd -> build\lib.win32-3.6\cytoolz
    copying cytoolz\utils.pxd -> build\lib.win32-3.6\cytoolz
    copying cytoolz\__init__.pxd -> build\lib.win32-3.6\cytoolz
    creating build\lib.win32-3.6\cytoolz\tests
    copying cytoolz\tests\dev_skip_test.py -> build\lib.win32-3.6\cytoolz\tests
    copying cytoolz\tests\test_compatibility.py -> build\lib.win32-3.6\cytoolz\tests
    copying cytoolz\tests\test_curried.py -> build\lib.win32-3.6\cytoolz\tests
    copying cytoolz\tests\test_curried_doctests.py -> build\lib.win32-3.6\cytoolz\tests
    copying cytoolz\tests\test_curried_toolzlike.py -> build\lib.win32-3.6\cytoolz\tests
    copying cytoolz\tests\test_dev_skip_test.py -> build\lib.win32-3.6\cytoolz\tests
    copying cytoolz\tests\test_dicttoolz.py -> build\lib.win32-3.6\cytoolz\tests
    copying cytoolz\tests\test_docstrings.py -> build\lib.win32-3.6\cytoolz\tests
    copying cytoolz\tests\test_doctests.py -> build\lib.win32-3.6\cytoolz\tests
    copying cytoolz\tests\test_embedded_sigs.py -> build\lib.win32-3.6\cytoolz\tests
    copying cytoolz\tests\test_functoolz.py -> build\lib.win32-3.6\cytoolz\tests
    copying cytoolz\tests\test_inspect_args.py -> build\lib.win32-3.6\cytoolz\tests
    copying cytoolz\tests\test_itertoolz.py -> build\lib.win32-3.6\cytoolz\tests
    copying cytoolz\tests\test_none_safe.py -> build\lib.win32-3.6\cytoolz\tests
    copying cytoolz\tests\test_recipes.py -> build\lib.win32-3.6\cytoolz\tests
    copying cytoolz\tests\test_serialization.py -> build\lib.win32-3.6\cytoolz\tests
    copying cytoolz\tests\test_signatures.py -> build\lib.win32-3.6\cytoolz\tests
    copying cytoolz\tests\test_tlz.py -> build\lib.win32-3.6\cytoolz\tests
    copying cytoolz\tests\test_utils.py -> build\lib.win32-3.6\cytoolz\tests
    running build_ext
    building 'cytoolz.dicttoolz' extension
    creating build\temp.win32-3.6
    creating build\temp.win32-3.6\Release
    creating build\temp.win32-3.6\Release\cytoolz
    cl.exe /c /nologo /Ox /W3 /GL /DNDEBUG /MD -Ic:\users\administrador\appdata\local\programs\python\python36-32\include -Ic:\users\administrador\appdata\local\programs\python\python36-32\include /Tccytoolz/dicttoolz.c /Fobuild\temp.win32-3.6\Release\cytoolz/dicttoolz.obj
    error: command 'cl.exe' failed: No such file or directory

    ----------------------------------------
Command "c:\users\administrador\appdata\local\programs\python\python36-32\python.exe -u -c "import setuptools, tokenize;__file__='C:\\Users\\ADMINI~1\\AppData\\Local\\Temp\\pip-build-qk95p6mk\\cytoolz\\setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record C:\Users\ADMINI~1\AppData\Local\Temp\pip-5td6dish-record\install-record.txt --single-version-externally-managed --compile" failed with error code 1 in C:\Users\ADMINI~1\AppData\Local\Temp\pip-build-qk95p6mk\cytoolz\

**Comment by adamyala** [comment]
This full stack trace you posted is for different errors than the one in the issue title.

Which error specifically are you trying to solve?

**Comment by djalmabright** [comment]
Hi adamyala really  the first  problem  was  the   before title  post  however  I  could  fix it    however  now  Windows  10  System  in all  machines that  I  use  display  this  same  error  always   when  I  try  install   dependencies 👍 
pip install -r requirements.txt  
..............................
Requirement already satisfied: certifi==2017.11.5 in c:\users\administrador\appdata\local\programs\python\python36-32\lib\site-packages (from -r requirements.txt (line 1))
Requirement already satisfied: chardet==3.0.4 in c:\users\administrador\appdata\local\programs\python\python36-32\lib\site-packages (from -r requirements.txt (line 2))
Requirement already satisfied: click==6.7 in c:\users\administrador\appdata\local\programs\python\python36-32\lib\site-packages (from -r requirements.txt (line 3))
Collecting eth-abi==0.5.0 (from -r requirements.txt (line 4))
  Using cached eth_abi-0.5.0-py3-none-any.whl
Collecting eth-keyfile==0.4.1 (from -r requirements.txt (line 5))
  Using cached eth_keyfile-0.4.1-py3-none-any.whl
Collecting eth-keys==0.1.0b4 (from -r requirements.txt (line 6))
  Using cached eth_keys-0.1.0b4-py3-none-any.whl
Collecting eth-tester==0.1.0b11 (from -r requirements.txt (line 7))
  Using cached eth_tester-0.1.0b11-py3-none-any.whl
Collecting eth-utils==0.7.4 (from -r requirements.txt (line 8))
  Using cached eth_utils-0.7.4-py3-none-any.whl
Collecting Flask==0.12.2 (from -r requirements.txt (line 9))
  Using cached Flask-0.12.2-py2.py3-none-any.whl
Collecting idna==2.6 (from -r requirements.txt (line 10))
  Using cached idna-2.6-py2.py3-none-any.whl
Collecting itsdangerous==0.24 (from -r requirements.txt (line 11))
  Using cached itsdangerous-0.24.tar.gz
Collecting Jinja2==2.10 (from -r requirements.txt (line 12))
  Using cached Jinja2-2.10-py2.py3-none-any.whl
Collecting lru-dict==1.1.6 (from -r requirements.txt (line 13))
  Using cached lru-dict-1.1.6.tar.gz
Collecting MarkupSafe==1.0 (from -r requirements.txt (line 14))
  Using cached MarkupSafe-1.0.tar.gz
Collecting py-solc==2.1.0 (from -r requirements.txt (line 15))
  Using cached py_solc-2.1.0-py3-none-any.whl
Collecting pycryptodome==3.4.7 (from -r requirements.txt (line 16))
  Using cached pycryptodome-3.4.7-cp36-cp36m-win32.whl
Requirement already satisfied: pysha3==1.0.2 in c:\users\administrador\appdata\local\programs\python\python36-32\lib\site-packages (from -r requirements.txt (line 17))
Collecting requests==2.18.4 (from -r requirements.txt (line 18))
  Using cached requests-2.18.4-py2.py3-none-any.whl
Collecting rlp==0.6.0 (from -r requirements.txt (line 19))
  Using cached rlp-0.6.0.tar.gz
Collecting semantic-version==2.6.0 (from -r requirements.txt (line 20))
  Using cached semantic_version-2.6.0-py3-none-any.whl
Requirement already satisfied: toolz==0.9.0 in c:\users\administrador\appdata\local\programs\python\python36-32\lib\site-packages (from -r requirements.txt (line 21))
Collecting urllib3==1.22 (from -r requirements.txt (line 22))
  Using cached urllib3-1.22-py2.py3-none-any.whl
Collecting web3==4.0.0b5 (from -r requirements.txt (line 23))
  Using cached web3-4.0.0b5-py3-none-any.whl
Collecting Werkzeug==0.14.1 (from -r requirements.txt (line 24))
  Using cached Werkzeug-0.14.1-py2.py3-none-any.whl
Collecting cytoolz<1.0.0,>=0.9.0 (from eth-keyfile==0.4.1->-r requirements.txt (line 5))
  Using cached cytoolz-0.9.0.tar.gz
Installing collected packages: cytoolz, eth-utils, eth-abi, eth-keys, pycryptodome, eth-keyfile, semantic-version, rlp, eth-tester, MarkupSafe, Jinja2, itsdangerous, Werkzeug, Flask, idna, lru-dict, py-solc, urllib3, requests, web3
  Running setup.py install for cytoolz ... error
    Complete output from command c:\users\administrador\appdata\local\programs\python\python36-32\python.exe -u -c "import setuptools, tokenize;__file__='C:\\Users\\ADMINI~1\\AppData\\Local\\Temp\\pip-build-_ioj77am\\cytoolz\\setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record C:\Users\ADMINI~1\AppData\Local\Temp\pip-ely6qvn6-record\install-record.txt --single-version-externally-managed --compile:
    running install
    running build
    running build_py
    creating build
    creating build\lib.win32-3.6
    creating build\lib.win32-3.6\cytoolz
    copying cytoolz\compatibility.py -> build\lib.win32-3.6\cytoolz
    copying cytoolz\utils_test.py -> build\lib.win32-3.6\cytoolz
    copying cytoolz\_signatures.py -> build\lib.win32-3.6\cytoolz
    copying cytoolz\_version.py -> build\lib.win32-3.6\cytoolz
    copying cytoolz\__init__.py -> build\lib.win32-3.6\cytoolz
    creating build\lib.win32-3.6\cytoolz\curried
    copying cytoolz\curried\exceptions.py -> build\lib.win32-3.6\cytoolz\curried
    copying cytoolz\curried\operator.py -> build\lib.win32-3.6\cytoolz\curried
    copying cytoolz\curried\__init__.py -> build\lib.win32-3.6\cytoolz\curried
    copying cytoolz\dicttoolz.pyx -> build\lib.win32-3.6\cytoolz
    copying cytoolz\functoolz.pyx -> build\lib.win32-3.6\cytoolz
    copying cytoolz\itertoolz.pyx -> build\lib.win32-3.6\cytoolz
    copying cytoolz\recipes.pyx -> build\lib.win32-3.6\cytoolz
    copying cytoolz\utils.pyx -> build\lib.win32-3.6\cytoolz
    copying cytoolz\cpython.pxd -> build\lib.win32-3.6\cytoolz
    copying cytoolz\dicttoolz.pxd -> build\lib.win32-3.6\cytoolz
    copying cytoolz\functoolz.pxd -> build\lib.win32-3.6\cytoolz
    copying cytoolz\itertoolz.pxd -> build\lib.win32-3.6\cytoolz
    copying cytoolz\recipes.pxd -> build\lib.win32-3.6\cytoolz
    copying cytoolz\utils.pxd -> build\lib.win32-3.6\cytoolz
    copying cytoolz\__init__.pxd -> build\lib.win32-3.6\cytoolz
    creating build\lib.win32-3.6\cytoolz\tests
    copying cytoolz\tests\dev_skip_test.py -> build\lib.win32-3.6\cytoolz\tests
    copying cytoolz\tests\test_compatibility.py -> build\lib.win32-3.6\cytoolz\tests
    copying cytoolz\tests\test_curried.py -> build\lib.win32-3.6\cytoolz\tests
    copying cytoolz\tests\test_curried_doctests.py -> build\lib.win32-3.6\cytoolz\tests
    copying cytoolz\tests\test_curried_toolzlike.py -> build\lib.win32-3.6\cytoolz\tests
    copying cytoolz\tests\test_dev_skip_test.py -> build\lib.win32-3.6\cytoolz\tests
    copying cytoolz\tests\test_dicttoolz.py -> build\lib.win32-3.6\cytoolz\tests
    copying cytoolz\tests\test_docstrings.py -> build\lib.win32-3.6\cytoolz\tests
    copying cytoolz\tests\test_doctests.py -> build\lib.win32-3.6\cytoolz\tests
    copying cytoolz\tests\test_embedded_sigs.py -> build\lib.win32-3.6\cytoolz\tests
    copying cytoolz\tests\test_functoolz.py -> build\lib.win32-3.6\cytoolz\tests
    copying cytoolz\tests\test_inspect_args.py -> build\lib.win32-3.6\cytoolz\tests
    copying cytoolz\tests\test_itertoolz.py -> build\lib.win32-3.6\cytoolz\tests
    copying cytoolz\tests\test_none_safe.py -> build\lib.win32-3.6\cytoolz\tests
    copying cytoolz\tests\test_recipes.py -> build\lib.win32-3.6\cytoolz\tests
    copying cytoolz\tests\test_serialization.py -> build\lib.win32-3.6\cytoolz\tests
    copying cytoolz\tests\test_signatures.py -> build\lib.win32-3.6\cytoolz\tests
    copying cytoolz\tests\test_tlz.py -> build\lib.win32-3.6\cytoolz\tests
    copying cytoolz\tests\test_utils.py -> build\lib.win32-3.6\cytoolz\tests
    running build_ext
 building 'cytoolz.dicttoolz' extension
    creating build\temp.win32-3.6
    creating build\temp.win32-3.6\Release
    creating build\temp.win32-3.6\Release\cytoolz
    cl.exe /c /nologo /Ox /W3 /GL /DNDEBUG /MD -Ic:\users\administrador\appdata\local\programs\python\python36-32\include -Ic:\users\administrador\appdata\local\programs\python\python36-32\include /Tccytoolz/dicttoolz.c /Fobuild\temp.win32-3.6\Release\cytoolz/dicttoolz.obj
    error: command 'cl.exe' failed: No such file or directory

    ----------------------------------------
Command "c:\users\administrador\appdata\local\programs\python\python36-32\python.exe -u -c "import setuptools, tokenize;__file__='C:\\Users\\ADMINI~1\\AppData\\Local\\Temp\\pip-build-_ioj77am\\cytoolz\\setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record C:\Users\ADMINI~1\AppData\Local\Temp\pip-ely6qvn6-record\install-record.txt --single-version-externally-managed --compile" failed with error code 1 in C:\Users\ADMINI~1\AppData\Local\Temp\pip-build-_ioj77am\cytoolz\
This  is  FULL  stack  trace  I  got  !     
Thanks

**Comment by adamyala** [comment]
This seems to be a Windows/system issue and not related to the code in this repo. I'm marking this issue as closed for now.

Please check out https://stackoverflow.com/questions/41724445/python-pip-on-windows-command-cl-exe-failed This seems to be addressing the same issue.
